import os from "os";
import path from "path";
import fs from "fs";
import { GroveRegistry } from "./types.js";

// Generated shell file that grove rewrites on every plant/adopt/uproot.
export const ALIASES_FILE = path.join(os.homedir(), ".config", "grove-aliases.zsh");

const HEADER = [
  "# grove-managed shell aliases — DO NOT EDIT.",
  "# Regenerated by grove on every plant/adopt/uproot.",
  "# Source this from your ~/.zshrc:  source ~/.config/grove-aliases.zsh",
  "",
];

const SOURCE_LINE = "[ -f ~/.config/grove-aliases.zsh ] && source ~/.config/grove-aliases.zsh";

/**
 * Rewrite ~/.config/grove-aliases.zsh from the registry.
 *
 * For each project that declares an `aliases` map ({ prefix: subdir }), emit
 * `alias <prefix><slot>='cd <instance>/<subdir>'` for every instance, plus a
 * slot-0 alias pointing at the source (which mirrors the same subdir layout).
 */
export function regenerateAliases(registry: GroveRegistry): void {
  const lines: string[] = [...HEADER];

  for (const [projectName, proj] of Object.entries(registry.projects)) {
    if (!proj.aliases || Object.keys(proj.aliases).length === 0) continue;

    const targets: { slot: number; root: string }[] = [
      { slot: 0, root: proj.source }, // source is slot 0
      ...proj.instances.map((i) => ({ slot: i.slot, root: i.path })),
    ].sort((a, b) => a.slot - b.slot);

    lines.push(`# ${projectName}`);
    for (const { slot, root } of targets) {
      for (const [prefix, subdir] of Object.entries(proj.aliases)) {
        const dir = subdir === "." ? root : path.join(root, subdir);
        lines.push(`alias ${prefix}${slot}='cd ${JSON.stringify(dir)}'`);
      }
    }
    lines.push("");
  }

  fs.mkdirSync(path.dirname(ALIASES_FILE), { recursive: true });
  fs.writeFileSync(ALIASES_FILE, lines.join("\n") + "\n");

  ensureSourcedFromZshrc();
}

/** Append a `source` line to ~/.zshrc if it isn't already wired up. */
function ensureSourcedFromZshrc(): void {
  const zshrc = path.join(os.homedir(), ".zshrc");
  let content = "";
  try {
    content = fs.readFileSync(zshrc, "utf-8");
  } catch {
    // No ~/.zshrc — create one with just the source line.
  }
  if (content.includes("grove-aliases.zsh")) return;
  const addition = `${content.endsWith("\n") || content === "" ? "" : "\n"}\n# grove-managed aliases\n${SOURCE_LINE}\n`;
  fs.writeFileSync(zshrc, content + addition);
}
